application: ads-bpa-pulse
module: default
version: 1
runtime: go
api_version: go1
instance_class: F1
automatic_scaling:


handlers:
- url: /resources/
  static_dir: resources

- url: /.*
  script: _go_app
